spring.datasource.url=jdbc:mysql://localhost:3306/lalitha_surya_sweets
spring.datasource.username=root
spring.datasource.password=Developer123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yourmail@gmail.com
spring.mail.password=dev-app-password

logging.level.root=DEBUG

# WhatsApp Cloud API
whatsapp.access.token=dummy
whatsapp.phone.number.id=dummy
whatsapp.admin.number=919346771676