spring.datasource.url=jdbc:postgresql://ep-frosty-grass-ata0idrj.c-9.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_KTQEgl8ewa1X&sslmode=require&channelBinding=require
spring.datasource.username=ep-frosty-grass-ata0idrj.c-9.us-east-1.aws.neon.tech
spring.datasource.password=npg_KTQEgl8ewa1X
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=validate
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yourmail@gmail.com
spring.mail.password=dev-app-password

logging.level.root=DEBUG

# WhatsApp Cloud API
whatsapp.access.token=dummy
whatsapp.phone.number.id=dummy
whatsapp.admin.number=919346771676