spring.application.name=LalithaSweets
# ===============================
# DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/lalitha_surya_sweets
spring.datasource.username=root
spring.datasource.password=Developer123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA CONFIG
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ===============================
# SERVER
# ===============================
server.port=8080

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# ===============================
# GMAIL
# ===============================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=singidi.02@gmail.com
spring.mail.password=mlnqxgqmpvvzymab

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


spring.mail.properties.mail.debug=true


#-----------------------------------

spring.profiles.active=dev

#--------------------------------------

whatsapp.admin.number=919346771676

#-----------------------------------------

razorpay.key.id=rzp_test_SdycDDBz9s8JbW
razorpay.key.secret=hOmoZ6EX5R4XX3ct34C7xSUs























