package com.lalitha.sweets.model;

import java.util.List;

public enum OrderStatus {
	NEW,
	PENDING,
    PLACED,
    CONFIRMED,
    PREPARING,
    PACKED,
    SHIPPED,
    OUT_FOR_DELIVERY,
    DELIVERED,
    CANCELLED;
	
	public List<OrderStatus> nextAllowedStatuses(){
		return switch (this) {
		case NEW -> List.of(PENDING,PLACED,CONFIRMED,PREPARING,PACKED,SHIPPED,OUT_FOR_DELIVERY,DELIVERED,CANCELLED);
		case PENDING -> List.of(PLACED,CONFIRMED,PREPARING,PACKED,SHIPPED,OUT_FOR_DELIVERY,DELIVERED,CANCELLED);
		case PLACED -> List.of(CONFIRMED,PREPARING,PACKED,SHIPPED,OUT_FOR_DELIVERY,DELIVERED,CANCELLED);
		case CONFIRMED -> List.of(PREPARING,PACKED,SHIPPED,OUT_FOR_DELIVERY,DELIVERED,CANCELLED);
		case PREPARING -> List.of(PACKED,SHIPPED,OUT_FOR_DELIVERY,DELIVERED,CANCELLED);
		case PACKED -> List.of(SHIPPED,OUT_FOR_DELIVERY,DELIVERED,CANCELLED);
		case SHIPPED -> List.of(OUT_FOR_DELIVERY,DELIVERED,CANCELLED);
		case OUT_FOR_DELIVERY -> List.of(DELIVERED,CANCELLED);
		case DELIVERED,CANCELLED -> List.of();
		};
	}
}
